In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
a = pd.DataFrame(np.random.rand(4, 5), columns = list('abcde'))
a_asarray = a.values
print(a)
print(a_asarray)

          a         b         c         d         e
0  0.658220  0.895955  0.078877  0.965034  0.983096
1  0.636908  0.674697  0.431375  0.330668  0.683249
2  0.690070  0.055085  0.025047  0.066381  0.392422
3  0.956838  0.592932  0.884707  0.677090  0.008989
[[0.65821951 0.89595497 0.07887714 0.96503379 0.98309632]
 [0.63690788 0.67469712 0.43137461 0.33066759 0.68324851]
 [0.69007033 0.05508545 0.02504654 0.06638085 0.39242232]
 [0.95683765 0.59293165 0.88470736 0.67709023 0.00898894]]
